### ISSUE TITLE
Incompatible with RubyMine 2024.2

### ISSUE THREAD

**Issue by ryanseys** [simoleone/rubymine-sorbet-lsp#8]
![Screenshot 2024-08-15 at 2 33 54 PM](https://github.com/user-attachments/assets/8cb36222-809b-415b-9ae5-2faed1559073)

https://plugins.jetbrains.com/plugin/22388-sorbet-lsp

**Comment by simoleone** [comment]
Release 1.8 has been uploaded to Jetbrains (thanks, @mina-asham !). Their plugin verification process can take a day or two, unfortunately, but it will go live as soon as they approve it.

In the meantime, if you need to you you can snag the `.zip` from the [1.8 release page](https://github.com/simoleone/rubymine-sorbet-lsp/releases/tag/1.8) and pop that into RubyMine to get going quicker .

**Comment by simoleone** [comment]
They approved it pretty quickly. It's now live. https://plugins.jetbrains.com/plugin/22388-sorbet-lsp/versions/stable/589305
